# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dom\Desktop\CJ\ui_main_window2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1093, 774)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 710, 641, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.control_bt = QtWidgets.QPushButton(self.layoutWidget)
        self.control_bt.setObjectName("control_bt")
        self.verticalLayout.addWidget(self.control_bt)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(780, 160, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Parametr1 = QtWidgets.QLabel(Form)
        self.Parametr1.setGeometry(QtCore.QRect(780, 140, 131, 16))
        self.Parametr1.setObjectName("Parametr1")
        self.Parametr11 = QtWidgets.QLabel(Form)
        self.Parametr11.setGeometry(QtCore.QRect(900, 140, 31, 16))
        self.Parametr11.setObjectName("Parametr11")
        self.Biale = QtWidgets.QLabel(Form)
        self.Biale.setGeometry(QtCore.QRect(780, 60, 55, 16))
        self.Biale.setObjectName("Biale")
        self.Czarne = QtWidgets.QLabel(Form)
        self.Czarne.setGeometry(QtCore.QRect(780, 90, 55, 16))
        self.Czarne.setObjectName("Czarne")
        self.CzarneLiczba = QtWidgets.QLabel(Form)
        self.CzarneLiczba.setGeometry(QtCore.QRect(850, 60, 55, 16))
        self.CzarneLiczba.setObjectName("CzarneLiczba")
        self.CzarneLiczba_2 = QtWidgets.QLabel(Form)
        self.CzarneLiczba_2.setGeometry(QtCore.QRect(850, 90, 55, 16))
        self.CzarneLiczba_2.setObjectName("CzarneLiczba_2")
        self.ChanellLog = QtWidgets.QTextBrowser(Form)
        self.ChanellLog.setGeometry(QtCore.QRect(720, 501, 351, 181))
        self.ChanellLog.setObjectName("ChanellLog")
        self.Parametr22 = QtWidgets.QLabel(Form)
        self.Parametr22.setGeometry(QtCore.QRect(940, 280, 55, 16))
        self.Parametr22.setObjectName("Parametr22")
        self.Parametr2 = QtWidgets.QLabel(Form)
        self.Parametr2.setGeometry(QtCore.QRect(780, 280, 151, 16))
        self.Parametr2.setObjectName("Parametr2")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(780, 300, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.max_radius1 = QtWidgets.QLabel(Form)
        self.max_radius1.setGeometry(QtCore.QRect(900, 220, 55, 16))
        self.max_radius1.setObjectName("max_radius1")
        self.max_radius = QtWidgets.QLabel(Form)
        self.max_radius.setGeometry(QtCore.QRect(780, 220, 111, 16))
        self.max_radius.setObjectName("max_radius")
        self.horizontalSlider_3 = QtWidgets.QSlider(Form)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(780, 240, 160, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(Form)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(780, 380, 160, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.min_radius1 = QtWidgets.QLabel(Form)
        self.min_radius1.setGeometry(QtCore.QRect(900, 360, 55, 16))
        self.min_radius1.setObjectName("min_radius1")
        self.min_radius = QtWidgets.QLabel(Form)
        self.min_radius.setGeometry(QtCore.QRect(780, 360, 121, 16))
        self.min_radius.setObjectName("min_radius")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 661, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.image_label = QtWidgets.QLabel(self.tab_3)
        self.image_label.setEnabled(True)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 635, 635))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.image_label_4 = QtWidgets.QLabel(self.tab_4)
        self.image_label_4.setEnabled(True)
        self.image_label_4.setGeometry(QtCore.QRect(10, 330, 311, 311))
        self.image_label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label_4.setText("")
        self.image_label_4.setObjectName("image_label_4")
        self.image_label_5 = QtWidgets.QLabel(self.tab_4)
        self.image_label_5.setEnabled(True)
        self.image_label_5.setGeometry(QtCore.QRect(330, 330, 311, 311))
        self.image_label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label_5.setText("")
        self.image_label_5.setObjectName("image_label_5")
        self.image_label_6 = QtWidgets.QLabel(self.tab_4)
        self.image_label_6.setEnabled(True)
        self.image_label_6.setGeometry(QtCore.QRect(330, 10, 311, 311))
        self.image_label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label_6.setText("")
        self.image_label_6.setObjectName("image_label_6")
        self.image_label_7 = QtWidgets.QLabel(self.tab_4)
        self.image_label_7.setEnabled(True)
        self.image_label_7.setGeometry(QtCore.QRect(10, 10, 311, 311))
        self.image_label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label_7.setText("")
        self.image_label_7.setObjectName("image_label_7")
        self.tabWidget.addTab(self.tab_4, "")
        self.min_radius_2 = QtWidgets.QLabel(Form)
        self.min_radius_2.setGeometry(QtCore.QRect(720, 480, 121, 16))
        self.min_radius_2.setObjectName("min_radius_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(780, 440, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(720, 690, 93, 28))
        self.pushButton.setObjectName("pushButton")


        self.horizontalSlider.valueChanged.connect(self.v_horizontal1)

        self.horizontalSlider_2.valueChanged.connect(self.v_horizontal2)
        self.horizontalSlider_3.valueChanged.connect(self.v_horizontal3)
        self.horizontalSlider_4.valueChanged.connect(self.v_horizontal4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def v_horizontal1(self) :
        self.Parametr11.setText(str(self.horizontalSlider.value()))

    def v_horizontal2(self):
        self.Parametr22.setText(str(self.horizontalSlider_2.value()))
    def v_horizontal3(self):
        if ( self.horizontalSlider_3.value()<self.horizontalSlider_4.value()):
            self.horizontalSlider_4.setValue(self.horizontalSlider_3.value())
        self.max_radius1.setText(str(self.horizontalSlider_3.value()))
    def v_horizontal4(self):
        if ( self.horizontalSlider_3.value()<self.horizontalSlider_4.value()):
            self.horizontalSlider_3.setValue(self.horizontalSlider_4.value())
        self.min_radius1.setText(str(self.horizontalSlider_4.value()))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CheckersAnalyzer"))
        self.control_bt.setText(_translate("Form", "Start"))
        self.Parametr1.setText(_translate("Form", "Canny Treshold :"))
        self.Parametr11.setText(_translate("Form", "1"))
        self.Biale.setText(_translate("Form", "Białe: "))
        self.Czarne.setText(_translate("Form", "Czarne: "))
        self.CzarneLiczba.setText(_translate("Form", "None"))
        self.CzarneLiczba_2.setText(_translate("Form", "None"))
        self.Parametr22.setText(_translate("Form", "1"))
        self.Parametr2.setText(_translate("Form", "Accumulator threshold for Hough Gradient:"))
        self.max_radius1.setText(_translate("Form", "1"))
        self.max_radius.setText(_translate("Form", "Maximum radius :"))
        self.min_radius1.setText(_translate("Form", "1"))
        self.min_radius.setText(_translate("Form", "Minimum radius:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Steps"))
        self.min_radius_2.setText(_translate("Form", "Logs:"))
        self.checkBox.setText(_translate("Form", "Check moves"))
        self.pushButton.setText(_translate("Form", "Clear Logs"))
        self.horizontalSlider.setValue(40)
        self.horizontalSlider_2.setValue(40)
        self.horizontalSlider_3.setValue(24)
        self.horizontalSlider_4.setValue(20)


